import "/global.scss";

export const metadata = {
  title: "RealStatic",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="/icon/favicon.ico" rel="icon" type="image/x-icon" />
      </head>
      <body>{children}</body>
    </html>
  );
}
